language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
install:
  - pip install r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
scripts:
  - python test_entries.py
  - python test_users.py
  - nosetests --with-coverage
after_success:
  - coveralls