language: python

python:
  -'3.5'

install:
  - pip install r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
scripts:
  - python test_entries.py
  - python test_users.py
  - nosetests --with-coverage
after_success:
  - coveralls