language: python
python:
# only test against versions: 
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: "pip install -r requirements.txt"
  - pip install coveralls
  - pip install pytest-cov
before_script:
  - cd api/v2/tests
  - psql -c 'create database mydiary;' -U postgres
script: 
  - pytest
  - coverage run --source=api/v2/tests -m pytest && coverage report
after_success:
  - coveralls  

 